### ISSUE TITLE
Question about occluder

### ISSUE THREAD

**Issue by imabackstabber** [tiangexiang/OccNeRF#7]
Hi, I wanna ask about the design of the occluder used in this paper.
I read from the paper that 'Without losing generality, we simulate the presence of a box-like obstacle right in front of the camera that causes a rectangular area at the center of the frame to be occluded.'. And I think it should be look like this:
![image](https://github.com/tiangexiang/OccNeRF/assets/50511903/f173de71-50d1-4722-ae9e-3f8953264b62)
However, I ran the code and found out the occluder is somehow just a black value (RGB: [0,0,0]):
![image](https://github.com/tiangexiang/OccNeRF/assets/50511903/e86e6762-8da4-4b2a-8cfa-a6fecb705748)
I think the code told it to do so:
![image](https://github.com/tiangexiang/OccNeRF/assets/50511903/b0093c80-6dd8-4775-9f55-675b1424eb98)
So I wonder whether it should be like this(i.e, simply make the occluder black) or should I implement a version the same as the paper? If the latter option is required, how should I do it?

**Comment by tiangexiang** [comment]
Hi, yes, occluders are treated and processed as the codes implemented. Our intuition is that, when there is an occluder blocking the camera, blocked human body becomes invisible and undetectable by semantic segmentation models. In this way, we obtain an alpha mask that indicates transparency at the invisible parts include both background and occluded regions, which are being processed equally (blended according to `bg_color`) since they are no different in our methods.

**Comment by imabackstabber** [comment]
I see. Thanks for you reply!
